export const SHOW_ERROR = 'SHOW_ERROR';
export const RESET_ERROR = 'RESET_ERROR';

export const START_FETCHING = 'START_FETCHING';
export const STOP_FETCHING = 'STOP_FETCHING';

export const CONNECTION_FAILED = 'CONNECTION_FAILED';
export const CONNECTION_SUCCEEDED = 'CONNECTION_SUCCEEDED';
export const COULD_ACCESS_ACCOUNT = 'COULD_ACCESS_ACCOUNT';
export const COULD_NOT_ACCESS_ACCOUNT = 'COULD_NOT_ACCESS_ACCOUNT';

export const RECEIVE_BASIL = 'RECEIVE_BASIL';
export const RECEIVE_ACCOUNT = 'RECEIVE_ACCOUNT';
export const RECEIVE_ETHER_BALANCE = 'RECEIVE_ETHER_BALANCE';

export const ADD_DONATION = 'ADD_DONATION';
export const RESET_DONATION= 'RESET_DONATION';
export const RECEIVE_DONATION = 'RECEIVE_DONATION';

export const RECEIVE_TOKEN_BALANCE = 'RECEIVE_TOKEN_BALANCE';
